//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Agent
    {
        [Required]
        public int agentid { get; set; }
        [Required]
        [EmailAddress]
        public string agentmail { get; set; }
        [Required]
        [StringLength(8)]
        public string password { get; set; }
        public string agentname { get; set; }
        [Required]
        [StringLength(11)]
        public string agentcontact { get; set; }
        [Required]
        public string username { get; set; }
    }
}
