//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Host
    {
        public Host()
        {
            this.Users = new HashSet<User>();
        }
    
        public int hostid { get; set; }
        public string username { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string mobilenumber { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
