//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Hotel
    {
        [Required]
        public int hotelid { get; set; }
        [Required]
        public string hoteltype { get; set; }
        [Required]
        public string hotellocation { get; set; }
        [Required]
        public string hotelprice { get; set; }
    }
}
