//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int id { get; set; }
        public int clientid { get; set; }
        public string tokenaccess { get; set; }
        public System.DateTime Createdat { get; set; }
        public Nullable<System.DateTime> Expireat { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
